/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica5;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Cristian
 */
public class Practica5 extends javax.swing.JFrame {

    /**
     * Creates new form Practica5
     */
    public Practica5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lienzo = new practica5.Lienzo();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFichero = new javax.swing.JMenu();
        itemAbrir = new javax.swing.JMenuItem();
        itemGuardar = new javax.swing.JMenuItem();
        itemExit = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        itemAlumbrado = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemInformacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Umbralizado");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuFichero.setText("Fichero");

        itemAbrir.setText("Abrir ");
        itemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAbrirActionPerformed(evt);
            }
        });
        menuFichero.add(itemAbrir);

        itemGuardar.setText("Guardar");
        itemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGuardarActionPerformed(evt);
            }
        });
        menuFichero.add(itemGuardar);

        itemExit.setText("Salir");
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        menuFichero.add(itemExit);

        jMenuBar1.add(menuFichero);

        menuEditar.setText("Editar");

        itemAlumbrado.setText("Umbralizar");
        itemAlumbrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAlumbradoActionPerformed(evt);
            }
        });
        menuEditar.add(itemAlumbrado);

        jMenuBar1.add(menuEditar);

        menuAyuda.setText("Ayuda");

        itemInformacion.setText("Acerca de ..");
        itemInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInformacionActionPerformed(evt);
            }
        });
        menuAyuda.add(itemInformacion);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Imagen (*.jpg, *.png)", "jpg","png");
        file.addChoosableFileFilter(filter);
        file.setFileFilter(filter);
        
        int res = file.showOpenDialog(null);
        if(res == JFileChooser.APPROVE_OPTION)loadImage(file.getSelectedFile()); 
        
    }//GEN-LAST:event_itemAbrirActionPerformed
    
    private void loadImage(File file) {
        try {
            BufferedImage image = ImageIO.read(file);
            lienzo.setImagen(image);
            repaint();
        } catch (IOException ex) {
            Logger.getLogger(Practica5.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void itemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuardarActionPerformed
        // TODO add your handling code here:
        if(lienzo.getImagen() != null){
            JFileChooser file = new JFileChooser();
            file.setSelectedFile(new File("imagen.jpg"));
            int res = file.showSaveDialog(null);
            if(res == JFileChooser.APPROVE_OPTION)saveImage(file.getSelectedFile());
        }else{
            JOptionPane.showMessageDialog(rootPane, "Debe abrir una imagen "
                    + "primero", "Error al guardar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemGuardarActionPerformed

    private void saveImage(File file) {
        try {
            ImageIO.write(lienzo.getImagen(),"jpg",file);
        } catch (IOException ex) {
            Logger.getLogger(Practica5.class.getName()).log(Level.SEVERE, null, ex);
        }
    } 
    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(rootPane, "¿Seguro que quiere"
                + " salir?", "Salir",JOptionPane.OK_CANCEL_OPTION);
        if(answer == JOptionPane.OK_OPTION)System.exit(0);
    }//GEN-LAST:event_itemExitActionPerformed

    private void itemInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInformacionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Esta aplicación,tiene como principal"
                + "funcionalidad,\n umbralizar una imagen que hemos abierto a"
                + "través \n del menú.Además se podrá guardar la imagen resultante.", 
                "Informacion", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_itemInformacionActionPerformed

    private void itemAlumbradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlumbradoActionPerformed
        // TODO add your handling code here:
        if(lienzo.getImagen() != null){
            int value = Integer.parseInt((String)JOptionPane.showInputDialog(rootPane,"Intoduzca un "
                    + "valor para el umbralizado","Umbralizar",
                    JOptionPane.YES_NO_CANCEL_OPTION,null,null,100));
            BufferedImage imangenUmbralizada = lienzo.umbralizar(lienzo.getImagen(), value);
            lienzo.setImagen(imangenUmbralizada);
            repaint();  
        }else{
            JOptionPane.showMessageDialog(rootPane, "Debe abrir una imagen "
                    + "primero", "Error al umbralizar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemAlumbradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAbrir;
    private javax.swing.JMenuItem itemAlumbrado;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemGuardar;
    private javax.swing.JMenuItem itemInformacion;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private practica5.Lienzo lienzo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuFichero;
    // End of variables declaration//GEN-END:variables
}
