
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cristian
 */
public class Prac4 extends javax.swing.JFrame {

    /**
     * Creates new form Prac4
     */
    public Prac4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        imagePane = new javax.swing.JPanel();
        cocheBoton = new javax.swing.JRadioButton();
        avionBoton = new javax.swing.JRadioButton();
        motoBoton = new javax.swing.JRadioButton();
        decorationPane = new javax.swing.JPanel();
        resaltatCheck = new javax.swing.JCheckBox();
        difuminarCheck = new javax.swing.JCheckBox();
        contenedorPanel = new javax.swing.JPanel();
        panelMuestra = new panelMuestra();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagePane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)), "Elija una Imagen"));

        buttonGroup1.add(cocheBoton);
        cocheBoton.setText("Coche");
        cocheBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocheBotonActionPerformed(evt);
            }
        });

        buttonGroup1.add(avionBoton);
        avionBoton.setText("Avion");
        avionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avionBotonActionPerformed(evt);
            }
        });

        buttonGroup1.add(motoBoton);
        motoBoton.setText("Moto");
        motoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motoBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imagePaneLayout = new javax.swing.GroupLayout(imagePane);
        imagePane.setLayout(imagePaneLayout);
        imagePaneLayout.setHorizontalGroup(
            imagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePaneLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(imagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(motoBoton)
                    .addComponent(avionBoton)
                    .addComponent(cocheBoton))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        imagePaneLayout.setVerticalGroup(
            imagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cocheBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(avionBoton)
                .addGap(12, 12, 12)
                .addComponent(motoBoton)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        decorationPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)), "Efectos"));

        resaltatCheck.setText("Resaltar");
        resaltatCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                resaltatCheckItemStateChanged(evt);
            }
        });

        difuminarCheck.setText("Difuminar");
        difuminarCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                difuminarCheckItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout decorationPaneLayout = new javax.swing.GroupLayout(decorationPane);
        decorationPane.setLayout(decorationPaneLayout);
        decorationPaneLayout.setHorizontalGroup(
            decorationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decorationPaneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(decorationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(difuminarCheck)
                    .addComponent(resaltatCheck))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        decorationPaneLayout.setVerticalGroup(
            decorationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decorationPaneLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(resaltatCheck)
                .addGap(36, 36, 36)
                .addComponent(difuminarCheck)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        contenedorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)), "Imagen"));

        javax.swing.GroupLayout panelMuestraLayout = new javax.swing.GroupLayout(panelMuestra);
        panelMuestra.setLayout(panelMuestraLayout);
        panelMuestraLayout.setHorizontalGroup(
            panelMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        panelMuestraLayout.setVerticalGroup(
            panelMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout contenedorPanelLayout = new javax.swing.GroupLayout(contenedorPanel);
        contenedorPanel.setLayout(contenedorPanelLayout);
        contenedorPanelLayout.setHorizontalGroup(
            contenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        contenedorPanelLayout.setVerticalGroup(
            contenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(decorationPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(contenedorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenedorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(decorationPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cocheBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocheBotonActionPerformed
        loadImage("coche.jpg");
    }//GEN-LAST:event_cocheBotonActionPerformed

    private void avionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avionBotonActionPerformed
        // TODO add your handling code here:
        loadImage("avion.jpg");
    }//GEN-LAST:event_avionBotonActionPerformed

    private void motoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motoBotonActionPerformed
        // TODO add your handling code here:
        loadImage("moto.jpg");
    }//GEN-LAST:event_motoBotonActionPerformed

    private void resaltatCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_resaltatCheckItemStateChanged
        // TODO add your handling code here:
        try{
            if(resaltatCheck.isSelected()){
                panelMuestra.resaltar();
            }else{
                if(difuminarCheck.isSelected()){
                    panelMuestra.desResaltar(false);
                }else{
                    panelMuestra.desResaltar(true);
                }
            }
            repaint();
        }catch (RuntimeException ex){
            System.out.println("Debe seleccionar primero una foto");
        }
    }//GEN-LAST:event_resaltatCheckItemStateChanged

    private void difuminarCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_difuminarCheckItemStateChanged
        // TODO add your handling code here:
        try{
            if(difuminarCheck.isSelected()){
                panelMuestra.difuminar();
            }else{
                if(resaltatCheck.isSelected()){
                    panelMuestra.desDifuminar(false);
                }else{
                    panelMuestra.desDifuminar(true);
                }
            }
        repaint();    
        }catch(RuntimeException ex){
            System.out.println("Debe seleccionar primero una foto");
        }
    }//GEN-LAST:event_difuminarCheckItemStateChanged

    private void loadImage(String pathImage){
        try {
            resaltatCheck.setSelected(false);
            difuminarCheck.setSelected(false);
            BufferedImage imagen = ImageIO.read(new File(pathImage));
            panelMuestra.setImagen(imagen);
            repaint();
        } catch (IOException ex) {
            Logger.getLogger(Prac4.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prac4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prac4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prac4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prac4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prac4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton avionBoton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cocheBoton;
    private javax.swing.JPanel contenedorPanel;
    private javax.swing.JPanel decorationPane;
    private javax.swing.JCheckBox difuminarCheck;
    private javax.swing.JPanel imagePane;
    private javax.swing.JRadioButton motoBoton;
    private panelMuestra panelMuestra;
    private javax.swing.JCheckBox resaltatCheck;
    // End of variables declaration//GEN-END:variables
}
